# Author: Hung Vu

version: "3.8"

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      # Fill in secrets here in production
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks:
      - blogfolio
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

  caddy:
    container_name: caddy
    restart: always
    image: "ghcr.io/hunghvu/blogfolio-caddy:main"
    # build:
    #   context: .
    #   dockerfile: ./infras/containers/caddy/Dockerfile
    networks:
      - blogfolio
    environment:
      - CADDY_INGRESS_NETWORKS=blogfolio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 support https://caddyserver.com/docs/running#docker-compose
    labels:
      # Fill in secrets here in production
      # Not sure how to access via secrets though
      caddy.acme_dns: cloudflare

  web:
    container_name: web
    restart: always
    image: "ghcr.io/hunghvu/blogfolio-web:main"
    # build:
    #   context: .
    #   dockerfile: ./apps/web/Dockerfile
    networks:
      - blogfolio
    ports:
      - "3000:3000"
    labels:
      caddy: hungvu.tech
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.encode: zstd gzip

  cms:
    container_name: cms
    restart: always
    env_file: ./.env.production.local
    image: "ghcr.io/hunghvu/blogfolio-cms:main"
    # env_file: ./.env.production.local
    # build:
    #   context: .
    #   dockerfile: ./apps/cms/Dockerfile
    networks:
      - blogfolio
    ports:
      - "3100:3100"
    labels:
      caddy: payload.hungvu.tech
      caddy.reverse_proxy: "{{upstreams 3100}}"
      caddy.encode: zstd gzip

networks:
  # Network name cannot be "default"
  # And the network must be external, or else caddy cannot connect to other containers
  # Error: "container not in the same network as caddy" via "docker logs --follow caddy"
  blogfolio:
    driver: bridge
    external: true

volumes:
  caddy_data:
