version: "3.8"

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    networks:
      - default
    ports:
      - "3000:3000"

  cms:
    container_name: cms
    restart: always
    env_file: ./.env.production.local
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile
    networks:
      - default
    ports:
      - "3100:3100"

networks:
  default:
    driver: bridge