# Author: Hung Vu

version: "3.8"

services:
  caddy:
    container_name: caddy
    restart: always
    image: "ghcr.io/hunghvu/blogfolio-caddy:main"
    networks:
      - blogfolio
    environment:
      - CADDY_INGRESS_NETWORKS=blogfolio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 support https://caddyserver.com/docs/running#docker-compose

  web:
    container_name: web
    restart: always
    image: "ghcr.io/hunghvu/blogfolio-web:main"
    networks:
      - blogfolio
    ports:
      - "127.0.0.1:3000:3000"
    labels:
      # Cloudflared handles TLS termination (user -> Cloudflare Tunnel -> Caddy (server) -> Web (containers))
      # Users still reaches the server via HTTPS
      # But Caddy does not enable automatic TLS, because it is not public facing
      # Not sure if this affect the usage of HTTP/3 or not, probably not because Cloudflare handles it
      caddy: http://hungvu.tech
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.encode: zstd gzip

  cms:
    container_name: cms
    restart: always
    env_file: ./.env.production.local
    image: "ghcr.io/hunghvu/blogfolio-cms:main"
    networks:
      - blogfolio
    ports:
      - "127.0.0.1:3100:3100"
    labels:
      caddy: http://payload.hungvu.tech
      caddy.reverse_proxy: "{{upstreams 3100}}"
      caddy.encode: zstd gzip

networks:
  # Network name cannot be "default"
  # And the network must be external, or else caddy cannot connect to other containers
  # Error: "container not in the same network as caddy" via "docker logs --follow caddy"
  blogfolio:
    driver: bridge
    external: true

volumes:
  caddy_data:
