/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    articles: Article;
    media: Media;
    tags: Tag;
    series: Series;
    categories: Category;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Article {
  id: string;
  pageSettings: {
    settingsUrlSlug: string;
    settingsScheduledReleaseDate: string;
    settingsCategories: string | Category;
    settingsTags: string[] | Tag[];
    settingsSeries?: string | Series;
    settingsCoverImage: string | Media;
    settingsHideFromHome: 'yes' | 'no';
  };
  metaTitle: string;
  metaDescription: string;
  metaCustomOgImage?: string | Media;
  contentTitle: string;
  contentSubTitle: string;
  contentBody: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Category {
  id: string;
  categoriesTitle: string;
  categoriesDescription: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Tag {
  id: string;
  tagTitle: string;
  tagDescription: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Series {
  id: string;
  seriesTitle: string;
  seriesDescription: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    cover?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    og?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    body?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
